### ISSUE TITLE
We need plurals data from CLDR. 

### ISSUE THREAD

**Issue by akzhan** [perl-cldr/cldr-number-pm5#39]

**Comment by patch** [comment]
I don't plan on adding pluralization functionality to CLDR::Number since it's out of scope of the goals of this project. Take a look at the [*Pluralisation* section in Locale::CLDR](https://metacpan.org/pod/Locale::CLDR#Pluralisation) to see if that meets your needs. If not, I may be able to give suggestions if you provide more details on what you want to accomplish.
